import argparse
from pathlib import Path
import re
import unicodedata


def maybe_fix_mojibake(text: str) -> str:
    markers = ("â€™", "â€œ", "â€", "â€”", "â€“", "Ã©")
    if sum(text.count(marker) for marker in markers) < 5:
        return text
    try:
        return text.encode("cp1252").decode("utf-8")
    except UnicodeError:
        return text


def normalize_text(text: str) -> str:
    text = unicodedata.normalize("NFKC", maybe_fix_mojibake(text))
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u00a0": " ",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def is_wrapper_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if stripped == "TACTICAL MATCH ANALYSIS ARTICLES":
        return True
    if stripped.startswith("Generated by "):
        return True
    if re.fullmatch(r"=+", stripped):
        return True
    if re.fullmatch(r"ARTICLE\s+#\d+", stripped, flags=re.IGNORECASE):
        return True
    return False


def is_document_boundary(line: str) -> bool:
    stripped = line.strip()
    return bool(re.fullmatch(r"ARTICLE\s+#\d+", stripped, flags=re.IGNORECASE))


def paragraph_chunks(paragraphs: list[str], target_chars: int = 9000, max_chars: int = 14000) -> list[str]:
    docs = []
    current = []
    current_len = 0

    for paragraph in paragraphs:
        paragraph = " ".join(paragraph.split())
        if not paragraph:
            continue

        if current and current_len + len(paragraph) > target_chars:
            docs.append("\n\n".join(current))
            current = []
            current_len = 0

        current.append(paragraph)
        current_len += len(paragraph)

        if current_len >= max_chars:
            docs.append("\n\n".join(current))
            current = []
            current_len = 0

    if current:
        docs.append("\n\n".join(current))

    return docs


def extract_training_documents(raw_text: str, min_chars: int = 400) -> list[str]:
    text = normalize_text(raw_text).replace("\r\n", "\n").replace("\r", "\n")
    sections: list[list[str]] = []
    current_lines: list[str] = []

    for line in text.splitlines():
        if is_document_boundary(line) and current_lines:
            sections.append(current_lines)
            current_lines = []
            continue
        if is_wrapper_line(line):
            continue
        current_lines.append(line.rstrip())

    if current_lines:
        sections.append(current_lines)

    documents = []
    for section in sections:
        section_text = "\n".join(section).strip()
        if not section_text:
            continue
        paragraphs = [part.strip() for part in re.split(r"\n\s*\n+", section_text) if part.strip()]
        for doc in paragraph_chunks(paragraphs):
            if len(doc) >= min_chars:
                documents.append(doc)

    return documents


def build_clean_corpus(raw_file: str, clean_file: str, min_chars: int = 400) -> None:
    raw_path = Path(raw_file)
    out_path = Path(clean_file)
    if not raw_path.exists() or raw_path.stat().st_size == 0:
        raise FileNotFoundError(f"Raw corpus not found or empty: {raw_path}")

    documents = extract_training_documents(raw_path.read_text(encoding="utf-8", errors="replace"), min_chars)
    if not documents:
        raise ValueError("No training documents were found. Check the source text format.")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n\n\n".join(documents) + "\n", encoding="utf-8")
    print(f"Wrote {len(documents):,} cleaned training documents/sections to {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--raw", default="data/raw_tactical_match_analysis.txt")
    parser.add_argument("--out", default="data/tactics_corpus.txt")
    parser.add_argument("--min_chars", type=int, default=400)
    args = parser.parse_args()
    build_clean_corpus(args.raw, args.out, args.min_chars)


if __name__ == "__main__":
    main()
